id: P007034
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 12:37:33.031969
source_metadata:
  id: bdr:W29018
  title: སྙན་ངག་དང་མངོན་བརྗོད
  author: ''
  volumes:
    fb3c1029e4964b0283db4f638e731b62:
      image_group_id: I5741
      title: ''
      volume_number: 1
      total_pages: 834
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
