id: P007034
initial_creation_type: ocr
source_metadata:
  id: bdr:W29018
  title: སྙན་ངག་དང་མངོན་བརྗོད
  author: ''
  volumes:
    fb3c1029e4964b0283db4f638e731b62:
      image_group_id: I5741
      title: ''
      volume_number: 1
      total_pages: 834
ebook_metadata:
  title: སྙན་ངག་དང་མངོན་བརྗོད
  author: ''
  sku: P007034
  cover: cover.jpg
  layers:
  - pagination
